spring:
  security:
    user:
      name: ea
      password: cs544
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ea-final
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  jms:
    pub-sub-domain: true
  artemis:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
