spring:
  security:
    user:
      name: ea
      password: cs544
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  artemis:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
  jms:
    pub-sub-domain: true
  jpa:
    hibernate:
      ddl-auto: create
